# Generated by Django 3.1.5 on 2021-01-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_auto_20210129_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='send',
            new_name='sent_status',
        ),
    ]
